### ISSUE TITLE
Handle mapping between chromosomes and files

### ISSUE THREAD

**Issue by jsstevenson** [gks-anvil/vrsix#2]
In our initial use case, we have the comfort of a deterministic mapping between chromosomes and actual VCF files, i.e. `chr4` always exists only on a specific file named in a GREGoR data table.

I'm not sure we can take that for granted. Maybe joint callsets aren't available and everything actually is fragmented over per-patient VCFs. 

I also think we need to be designating some kind of file URI in addition to chromosomes regardless... otherwise it's not clear to me how you make the hop from getting a chr/pos for a VRS ID without hard-coding the place to extract the VCF row from.

**Comment by quinnwai** [comment]
Since we already have a tight coupling of VCF to index, would it make sense to make the values in the column the exact same as the VCF (eg chr1 instead of 1)? Editing the VRS ID to just use the hash makes sense but I don't think we should try and compress any of the other fields represented by the VCF.

**Comment by jsstevenson** [comment]
> Since we already have a tight coupling of VCF to index, would it make sense to make the values in the column the exact same as the VCF (eg chr1 instead of 1)? Editing the VRS ID to just use the hash makes sense but I don't think we should try and compress any of the other fields represented by the VCF.

Oh yeah, definitely agree -- I'm wondering if we need an additional column to associate to a file URI or something (since GREGoR data is spread across multiple files, we'd need someway to be like "this record is on `chr4`, that means it's in `gs://fc-secure-zzzzzzz-chr4`")
