### ISSUE TITLE
Writing CHROM directly rather than truncating the "chr" prefix

### ISSUE THREAD

**Issue by quinnwai** [gks-anvil/vrsix#22]
As a user, I want the chromosome (CHROM) string to be stored exactly as it is stored in the original VCF so that I know for sure whether a particular chromsome was labeled in the VCF as eg chr19 or 19 or otherwise.

**Comment by jsstevenson** [comment]
I think I originally did this for space-saving reasons. Maybe if this becomes a problem in the future, the main records table could store a truncated version and include a reference out to some kind of pattern (e.g. `chr*` to indicate a leading "chr" prefix) but that seems like unnecessary for now
